/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * asignatura.java
 *
 * Created on 31-may-2012, 23:31:22
 */
/**
 *
 * @author andres
 */
public class asignatura extends javax.swing.JFrame {

    /** Creates new form asignatura */
    public asignatura() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_salir = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_nuevo = new javax.swing.JMenuItem();
        menu_actualizar = new javax.swing.JMenuItem();
        menu_eliminar = new javax.swing.JMenuItem();

        setTitle("Modulo Asignatura");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asigntauras.jpg"))); // NOI18N

        menu_salir.setText("Archivo");

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_salir.add(jMenuItem4);

        jMenuBar1.add(menu_salir);

        jMenu2.setText("Gestionar");

        menu_nuevo.setText("Nuevo");
        menu_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_nuevoActionPerformed(evt);
            }
        });
        jMenu2.add(menu_nuevo);

        menu_actualizar.setText("Actualizar");
        menu_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_actualizarActionPerformed(evt);
            }
        });
        jMenu2.add(menu_actualizar);

        menu_eliminar.setText("Eliminar");
        menu_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_eliminarActionPerformed(evt);
            }
        });
        jMenu2.add(menu_eliminar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
this.hide();
}//GEN-LAST:event_jMenuItem4ActionPerformed

private void menu_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_nuevoActionPerformed
// TODO add your handling code here:
    nuevo_asignatura a = new nuevo_asignatura();
    a.setLocationRelativeTo(null);
    a.setVisible(true);
}//GEN-LAST:event_menu_nuevoActionPerformed

private void menu_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_actualizarActionPerformed
 actualizar_asignatura a = new actualizar_asignatura();
    a.setLocationRelativeTo(null);
    a.setVisible(true);
}//GEN-LAST:event_menu_actualizarActionPerformed

private void menu_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_eliminarActionPerformed
eliminar_asignatura a = new eliminar_asignatura();
    a.setLocationRelativeTo(null);
    a.setVisible(true);
}//GEN-LAST:event_menu_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new asignatura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menu_actualizar;
    private javax.swing.JMenuItem menu_eliminar;
    private javax.swing.JMenuItem menu_nuevo;
    private javax.swing.JMenu menu_salir;
    // End of variables declaration//GEN-END:variables
}
