/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frreportes.java
 *
 * Created on 06-jun-2012, 22:43:09
 */
/**
 *
 * @author andres
 */
public class frreportes extends javax.swing.JFrame {

    /** Creates new form frreportes */
    public frreportes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        bt_1 = new javax.swing.JMenuItem();
        bt_2 = new javax.swing.JMenuItem();
        bt_3 = new javax.swing.JMenuItem();
        bt_4 = new javax.swing.JMenuItem();
        bt_5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        bt_6 = new javax.swing.JMenuItem();
        bt_7 = new javax.swing.JMenuItem();
        bt_8 = new javax.swing.JMenuItem();
        bt_9 = new javax.swing.JMenuItem();
        bt_peorp = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        bt_10 = new javax.swing.JMenuItem();
        bt_12 = new javax.swing.JMenuItem();
        bt_13 = new javax.swing.JMenuItem();
        bt_menorcreditos = new javax.swing.JMenuItem();
        bt_11 = new javax.swing.JMenuItem();

        setTitle("Modulo Reportes");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30));
        jLabel1.setText("REPORTES");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes A");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        bt_1.setText(" CUANTOS ESTUDIANTES APROBARON EL SEMESTRE");
        bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1ActionPerformed(evt);
            }
        });
        jMenu2.add(bt_1);

        bt_2.setText("CUANTOS ESTUDIANTES REPROBARON EL SEMESTRE");
        bt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_2ActionPerformed(evt);
            }
        });
        jMenu2.add(bt_2);

        bt_3.setText("CUANTAS ASIGNATURAS TIPO A HAY Y CUAL ES LA SUMA DE SUS CRÉDITOS");
        bt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_3ActionPerformed(evt);
            }
        });
        jMenu2.add(bt_3);

        bt_4.setText("CUANTAS ASIGNATURAS TIPO B HAY Y CUAL ES LA SUMA DE SUS CRÉDITOS");
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });
        jMenu2.add(bt_4);

        bt_5.setText("CUANTOS ESTUDIANTES OBTUVIERON PROMEDIO PONDERADO INFERIOR A 2.0");
        bt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_5ActionPerformed(evt);
            }
        });
        jMenu2.add(bt_5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes B");

        bt_6.setText("CUANTOS ESTUDIANTES OBTUVIERON PROMEDIO PONDERADO ENTRE 2.0 Y MENOR A 3.0");
        bt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_6ActionPerformed(evt);
            }
        });
        jMenu3.add(bt_6);

        bt_7.setText("CUANTOS ESTUDIANTES OBTUVIERON PROMEDIO PONDERADO ENTRE 3.0 Y MENOR A 4.0.");
        bt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_7ActionPerformed(evt);
            }
        });
        jMenu3.add(bt_7);

        bt_8.setText("CUANTOS ESTUDIANTES OBTUVIERON PROMEDIO PONDERADO ENTRE 4.0 Y 5.0");
        bt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_8ActionPerformed(evt);
            }
        });
        jMenu3.add(bt_8);

        bt_9.setText("ESTUDIANTE QUE OBTUVO EL MEJOR PROMEDIO PONDERADO DEL CURSO Y CUÁL FUE ESE PROMEDIO");
        bt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_9ActionPerformed(evt);
            }
        });
        jMenu3.add(bt_9);

        bt_peorp.setText("ESTUDIANTE QUE OBTUVO EL PEOR PROMEDIO PONDERADO DEL Y CUÀL FUE ESE PROMEDIO");
        bt_peorp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_peorpActionPerformed(evt);
            }
        });
        jMenu3.add(bt_peorp);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes C");

        bt_10.setText("CUAL ES EL PROMEDIO DE LOS PROMEDIOS PONDERADOS");
        bt_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_10ActionPerformed(evt);
            }
        });
        jMenu4.add(bt_10);

        bt_12.setText("CUANTOS CREDITOS APROBARON LOS ESTUDIANTES QUE APROBARON EL SEMESTRE");
        bt_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_12ActionPerformed(evt);
            }
        });
        jMenu4.add(bt_12);

        bt_13.setText("CUANTOS CREDITOS APROBARON LOS ESTUDIANTES QUE REPROBARON EL SEMESTRE");
        bt_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_13ActionPerformed(evt);
            }
        });
        jMenu4.add(bt_13);

        bt_menorcreditos.setText("CUAL ES LA ASIGNATURA CON MENOR CANTIDAD DE CREDITOS");
        bt_menorcreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menorcreditosActionPerformed(evt);
            }
        });
        jMenu4.add(bt_menorcreditos);

        bt_11.setText("CUAL ES LA ASIGNATURA CON MAYOR CANTIDAD DE CREDITOS");
        bt_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_11ActionPerformed(evt);
            }
        });
        jMenu4.add(bt_11);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1ActionPerformed
        //Estudiantes que aprobaron
        
        
        Reporte.Archivo="Estudiantes_aprobados.html";
        Reporte.SQL="SELECT e.EST_COD_MATRICULA, UPPER(e.EST_NOMBRES), UPPER(e.EST_APELLIDOS), ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) "
                + "FROM SIA_NOTAS n "
                + "INNER JOIN SIA_PROYECCIONES p ON n.PRO_CODIGO=p.PRO_CODIGO "
                + "INNER JOIN SIA_ASIGNATURAS a ON p.ASI_CODIGO=a.ASI_CODIGO "
                + "INNER JOIN SIA_ESTUDIANTES e ON e.EST_CODIGO=p.EST_CODIGO "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) >= 3 AND e.est_estado = 1 "
                + "GROUP BY e.EST_CODIGO, e.EST_COD_MATRICULA, e.EST_NOMBRES, e.EST_APELLIDOS "
                + "ORDER BY e.EST_CODIGO"; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=4;
        String V[]={"CODIGO","NOMBRES", "APELLIDOS","P. PONDERADO"};
        Reporte.Titulo="Estudiantes Aprobados";
        Reporte.ReportHTML(V);
        
    }//GEN-LAST:event_bt_1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
     
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void bt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_2ActionPerformed
//Estudiantes que reprobaron
        
        
        Reporte.Archivo="Estudiantes_reprobados.html";
        Reporte.SQL="SELECT e.EST_COD_MATRICULA, UPPER(e.EST_NOMBRES), UPPER(e.EST_APELLIDOS), ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) "
                + "FROM SIA_NOTAS n "
                + "INNER JOIN SIA_PROYECCIONES p ON n.PRO_CODIGO=p.PRO_CODIGO "
                + "INNER JOIN SIA_ASIGNATURAS a ON p.ASI_CODIGO=a.ASI_CODIGO "
                + "INNER JOIN SIA_ESTUDIANTES e ON e.EST_CODIGO=p.EST_CODIGO "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) < 3 AND e.est_estado = 1 "
                + "GROUP BY e.EST_CODIGO, e.EST_COD_MATRICULA, e.EST_NOMBRES, e.EST_APELLIDOS "
                + "ORDER BY e.EST_CODIGO"; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=4;
        String V[]={"CODIGO","NOMBRES", "APELLIDOS","P. PONDERADO"};
        Reporte.Titulo="Estudiantes Reprobados";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_2ActionPerformed

    private void bt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_3ActionPerformed
        
        Reporte.Archivo="asignatura_tipo_a.html";
        Reporte.SQL="SELECT fn_cantidad_asi_tipo('A'), fn_suma_credi_tipo('A') "
                + "FROM  SIA_ASIGNATURAS "
                + "WHERE ASI_TIPO='A' "
                + "GROUP BY ASI_TIPO "; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=2;
        String V[]={"CANTIDAD", "SUMA TOTAL"};
        Reporte.Titulo="Asignaturas Tipo A";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_3ActionPerformed

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
      Reporte.Archivo="asignatura_tipo_b.html";
        Reporte.SQL="SELECT fn_cantidad_asi_tipo('B'), fn_suma_credi_tipo('B') "
                + "FROM  SIA_ASIGNATURAS "
                + "WHERE ASI_TIPO='B' "
                + "GROUP BY ASI_TIPO "; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=2;
        String V[]={"CANTIDAD", "SUMA TOTAL"};
        Reporte.Titulo="Asignaturas Tipo B";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_5ActionPerformed
        
        Reporte.Archivo="estudiantes_menores_a_2.html";
        Reporte.SQL="SELECT count(e.est_codigo) "
                + "FROM SIA_ESTUDIANTES e "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) < 2 AND e.est_estado =1";
                
                
        Reporte.Logo="images/logo.png";
        Reporte.ncol=1;
        String V[]={"CANTIDAD"};
        Reporte.Titulo="Cantidad Estudiantes P.P. Menores a 2.0";
        Reporte.ReportHTML(V);
        
    }//GEN-LAST:event_bt_5ActionPerformed

    private void bt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_6ActionPerformed
       Reporte.Archivo="estudiantes_entre2y3.html";
        Reporte.SQL="SELECT count(*) "
                + "FROM SIA_ESTUDIANTES e  "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) "
                + "BETWEEN 2 AND 2.9 AND e.est_estado=1 ";
        Reporte.Logo="images/logo.png";
        Reporte.ncol=1;
        String V[]={"CANTIDAD"};
        Reporte.Titulo="Cantidad Estudiantes P.P. Entre 2 y menores a 3";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_6ActionPerformed

    private void bt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_7ActionPerformed
         Reporte.Archivo="estudiantes_entre3y4.html";
        Reporte.SQL="SELECT count(*) "
                + "FROM SIA_ESTUDIANTES e "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) < 4 AND "
                + "ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) >= 3 AND e.est_estado=1 " ;
        Reporte.Logo="images/logo.png";
        Reporte.ncol=1;
        String V[]={"CANTIDAD"};
        Reporte.Titulo="Cantidad Estudiantes P.P. Entre 3 y menores a 4";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_7ActionPerformed

    private void bt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_8ActionPerformed
        Reporte.Archivo="estudiantes_entre4y5.html";
        Reporte.SQL="SELECT count(*) "
                + "FROM SIA_ESTUDIANTES e "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) >= 4 "
                + "AND e.est_estado=1 ";
        Reporte.Logo="images/logo.png";
        Reporte.ncol=1;
        String V[]={"CANTIDAD"};
        Reporte.Titulo="Cantidad Estudiantes P.P. Entre 4 y 5";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_8ActionPerformed

    private void bt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_9ActionPerformed
       //TODO Falta terminar esta consulta
        
        Reporte.Archivo="Estudiante_mejorPP.html";
        Reporte.SQL="SELECT UPPER(e.EST_NOMBRES), UPPER(e.EST_APELLIDOS), ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),2) "
                + "FROM SIA_NOTAS n "
                + "INNER JOIN SIA_PROYECCIONES p ON n.PRO_CODIGO=p.PRO_CODIGO "
                + "INNER JOIN SIA_ASIGNATURAS a ON p.ASI_CODIGO=a.ASI_CODIGO "
                + "INNER JOIN SIA_ESTUDIANTES e ON e.EST_CODIGO=p.EST_CODIGO "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) = (SELECT MAX(ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1)) "
                + "FROM SIA_NOTAS n "
                + "INNER JOIN SIA_PROYECCIONES p ON n.PRO_CODIGO=p.PRO_CODIGO "
                + "INNER JOIN SIA_ASIGNATURAS a ON p.ASI_CODIGO=a.ASI_CODIGO "
                + "INNER JOIN SIA_ESTUDIANTES e ON e.EST_CODIGO=p.EST_CODIGO "
                + "WHERE e.est_estado = 1) "
                + "AND e.est_estado = 1 "
                + "GROUP BY e.EST_CODIGO, e.EST_NOMBRES, e.EST_APELLIDOS "
                + "ORDER BY e.EST_CODIGO"; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=3;
        String V[]={"NOMBRES", "APELLIDOS","P. PONDERADO"};
        Reporte.Titulo="Estudiantes Mejor Ponderado";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_9ActionPerformed

    private void bt_peorpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_peorpActionPerformed
      Reporte.Archivo="Estudiante_peorPP.html";
        Reporte.SQL="SELECT UPPER(e.EST_NOMBRES), UPPER(e.EST_APELLIDOS), ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),2) "
                + "FROM SIA_NOTAS n "
                + "INNER JOIN SIA_PROYECCIONES p ON n.PRO_CODIGO=p.PRO_CODIGO "
                + "INNER JOIN SIA_ASIGNATURAS a ON p.ASI_CODIGO=a.ASI_CODIGO "
                + "INNER JOIN SIA_ESTUDIANTES e ON e.EST_CODIGO=p.EST_CODIGO "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) = (SELECT MIN(ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1)) "
                + "FROM SIA_NOTAS n "
                + "INNER JOIN SIA_PROYECCIONES p ON n.PRO_CODIGO=p.PRO_CODIGO "
                + "INNER JOIN SIA_ASIGNATURAS a ON p.ASI_CODIGO=a.ASI_CODIGO "
                + "INNER JOIN SIA_ESTUDIANTES e ON e.EST_CODIGO=p.EST_CODIGO "
                + "WHERE e.est_estado = 1) "
                + "AND e.est_estado = 1 "
                + "GROUP BY e.EST_CODIGO, e.EST_NOMBRES, e.EST_APELLIDOS "
                + "ORDER BY e.EST_CODIGO"; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=3;
        String V[]={"NOMBRES", "APELLIDOS","P. PONDERADO"};
        Reporte.Titulo="Estudiantes Peor Ponderado";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_peorpActionPerformed

    private void bt_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_10ActionPerformed
        Reporte.Archivo="Promedio_ponderado.html";
        Reporte.SQL="SELECT AVG(ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1)) "
                + "FROM SIA_NOTAS n "
                + "INNER JOIN SIA_PROYECCIONES p ON n.PRO_CODIGO=p.PRO_CODIGO "
                + "INNER JOIN SIA_ASIGNATURAS a ON p.ASI_CODIGO=a.ASI_CODIGO "
                + "INNER JOIN SIA_ESTUDIANTES e ON e.EST_CODIGO=p.EST_CODIGO "
                + "WHERE e.est_estado = 0 "
                + "GROUP BY e.EST_CODIGO, e.EST_COD_MATRICULA, e.EST_NOMBRES, e.EST_APELLIDOS "
                + "ORDER BY e.EST_CODIGO"; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=1;
        String V[]={"P. PONDERADO"};
        Reporte.Titulo="Promedio Ponderado";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_10ActionPerformed

    private void bt_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_12ActionPerformed
       //CUANTOS CREDITOS APROBARON LOS ESTUDIANTES QUE APROBARON EL SEMESTRE
         Reporte.Archivo="cre_aprobados-estudiantes_aprobados.html";
        Reporte.SQL="SELECT e.EST_COD_MATRICULA, UPPER(e.EST_NOMBRES), UPPER(e.EST_APELLIDOS), fn_suma_creditos_aprov(e.est_codigo) "
                + "FROM SIA_NOTAS n "
                + "INNER JOIN SIA_PROYECCIONES p ON n.PRO_CODIGO=p.PRO_CODIGO "
                + "INNER JOIN SIA_ASIGNATURAS a ON p.ASI_CODIGO=a.ASI_CODIGO "
                + "INNER JOIN SIA_ESTUDIANTES e ON e.EST_CODIGO=p.EST_CODIGO "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) >= 3 "
                + "AND e.est_estado = 1 "
                + "GROUP BY e.EST_CODIGO, e.EST_COD_MATRICULA, e.EST_NOMBRES, e.EST_APELLIDOS "
                + "ORDER BY e.EST_CODIGO"; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=4;
        String V[]={"CODIGO","NOMBRES", "APELLIDOS","CREDITOS APROBADOS"};
        Reporte.Titulo="Creditos Aprobados - Estudiantes Aprobados";
        Reporte.ReportHTML(V);
        
        
    }//GEN-LAST:event_bt_12ActionPerformed

    private void bt_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_13ActionPerformed
        Reporte.Archivo="cre_aprobados-estudiantes_reprobados.html";
        Reporte.SQL="SELECT e.EST_COD_MATRICULA, UPPER(e.EST_NOMBRES), UPPER(e.EST_APELLIDOS), NVL(fn_suma_creditos_aprov(e.est_codigo),0) "
                + "FROM SIA_NOTAS n "
                + "INNER JOIN SIA_PROYECCIONES p ON n.PRO_CODIGO=p.PRO_CODIGO "
                + "INNER JOIN SIA_ASIGNATURAS a ON p.ASI_CODIGO=a.ASI_CODIGO "
                + "INNER JOIN SIA_ESTUDIANTES e ON e.EST_CODIGO=p.EST_CODIGO "
                + "WHERE ROUND(fn_multiplicacion(e.est_codigo)/fn_suma_creditos(e.est_codigo),1) < 3 "
                + "AND e.est_estado = 1 "
                + "GROUP BY e.EST_CODIGO, e.EST_COD_MATRICULA, e.EST_NOMBRES, e.EST_APELLIDOS "
                + "ORDER BY e.EST_CODIGO"; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=3;
        String V[]={"CODIGO","NOMBRES", "APELLIDOS","CREDITOS APROBADOS"};
        Reporte.Titulo="Creditos Aprobados - Estudiantes Reprobados";
        Reporte.ReportHTML(V);
    }//GEN-LAST:event_bt_13ActionPerformed

    private void bt_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_11ActionPerformed
       
          Reporte.Archivo="asignaturas_mayor_creditos.html";
        Reporte.SQL="SELECT a.asi_codigo, a.ASI_NOMBRE, a.asi_creditos "
                + "FROM  SIA_ASIGNATURAS a "
                + "WHERE a.ASI_ESTADO=1 "
                + "AND a.ASI_CREDITOS=(SELECT max(a.asi_creditos) "
                + "FROM  SIA_ASIGNATURAS a "
                + "WHERE a.ASI_ESTADO=1)"; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=3;
        String V[]={"CODIGO ASIGNATURA","ASIGNATURAS", "CREDITOS"};
        Reporte.Titulo="Asignatura con mayor creditos";
        Reporte.ReportHTML(V);
        
    }//GEN-LAST:event_bt_11ActionPerformed

    private void bt_menorcreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menorcreditosActionPerformed
        //asignatura con menor creditos
        
        Reporte.Archivo="asignaturas_menor_creditos.html";
        Reporte.SQL="SELECT a.asi_codigo, a.ASI_NOMBRE, a.asi_creditos "
                + "FROM  SIA_ASIGNATURAS a "
                + "WHERE a.ASI_ESTADO=1 "
                + "AND a.ASI_CREDITOS=(SELECT min(a.asi_creditos) "
                + "FROM  SIA_ASIGNATURAS a "
                + "WHERE a.ASI_ESTADO=1)"; 
        Reporte.Logo="images/logo.png";
        Reporte.ncol=3;
        String V[]={"CODIGO ASIGNATURA","ASIGNATURAS", "CREDITOS"};
        Reporte.Titulo="Asignatura con menor creditos";
        Reporte.ReportHTML(V);
        
    }//GEN-LAST:event_bt_menorcreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frreportes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bt_1;
    private javax.swing.JMenuItem bt_10;
    private javax.swing.JMenuItem bt_11;
    private javax.swing.JMenuItem bt_12;
    private javax.swing.JMenuItem bt_13;
    private javax.swing.JMenuItem bt_2;
    private javax.swing.JMenuItem bt_3;
    private javax.swing.JMenuItem bt_4;
    private javax.swing.JMenuItem bt_5;
    private javax.swing.JMenuItem bt_6;
    private javax.swing.JMenuItem bt_7;
    private javax.swing.JMenuItem bt_8;
    private javax.swing.JMenuItem bt_9;
    private javax.swing.JMenuItem bt_menorcreditos;
    private javax.swing.JMenuItem bt_peorp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
