/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * prestamo.java
 *
 * Created on 21/11/2009, 04:52:40 PM
 */

/**
 *
 * @author Edgardo
 */
import java.sql.*;
import javax.swing.table.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
public class prestamo extends javax.swing.JFrame {
private int v[];
    /** Creates new form prestamo */
    public prestamo() {
        initComponents();
        DataBase.Open();
        dateentre.setText(fecha());
        datedevol.setText(fecha2());

       
       

    }
    public String fecha(){
         Calendar c = new GregorianCalendar();
                     String dia, mes, annio;
                     dia = Integer.toString(c.get(Calendar.DATE));
                     mes = Integer.toString(c.get(Calendar.MONTH)+1);
                     annio = Integer.toString(c.get(Calendar.YEAR));

                     String fecha= annio+ "/" + mes +"/" + dia;
                     return fecha;
    }
    public String fecha2(){
         Calendar c = new GregorianCalendar();
                     String dia, mes, annio;
                     dia = Integer.toString(c.get(Calendar.DATE)+2);
                     mes = Integer.toString(c.get(Calendar.MONTH)+1);
                     annio = Integer.toString(c.get(Calendar.YEAR));

                     String fecha= annio+ "/" + mes +"/" + dia;
                     return fecha;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frcliente = new javax.swing.JFrame();
        btaceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txbuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        frarticulo = new javax.swing.JFrame();
        btaceptar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaART = new javax.swing.JTable();
        txbuscarART = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btcliente = new javax.swing.JButton();
        btarticulo = new javax.swing.JButton();
        txarticulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtipo = new javax.swing.JTextField();
        txcodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btprestar = new javax.swing.JButton();
        dateentre = new javax.swing.JTextField();
        datedevol = new javax.swing.JTextField();

        frcliente.setBounds(new java.awt.Rectangle(0, 0, 399, 310));

        btaceptar.setText("Aceptar");
        btaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaceptarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cedula", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        txbuscar.setText("Escribe aqui");
        txbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbuscarActionPerformed(evt);
            }
        });
        txbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txbuscarKeyPressed(evt);
            }
        });

        jLabel7.setText("Buscar");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24));
        jLabel8.setText("Clientes");

        javax.swing.GroupLayout frclienteLayout = new javax.swing.GroupLayout(frcliente.getContentPane());
        frcliente.getContentPane().setLayout(frclienteLayout);
        frclienteLayout.setHorizontalGroup(
            frclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frclienteLayout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(btaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(frclienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frclienteLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        frclienteLayout.setVerticalGroup(
            frclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frclienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btaceptar)
                .addGap(36, 36, 36))
        );

        frarticulo.setBounds(new java.awt.Rectangle(0, 0, 527, 320));

        btaceptar1.setText("Aceptar");
        btaceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaceptar1ActionPerformed(evt);
            }
        });

        tablaART.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Asignatura", "Tipo", "Autor", "Tema", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaART.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaARTMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaART);

        txbuscarART.setText("Escribe aqui");
        txbuscarART.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbuscarARTActionPerformed(evt);
            }
        });
        txbuscarART.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txbuscarARTKeyPressed(evt);
            }
        });

        jLabel9.setText("Buscar");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24));
        jLabel10.setText("Articulos");

        javax.swing.GroupLayout frarticuloLayout = new javax.swing.GroupLayout(frarticulo.getContentPane());
        frarticulo.getContentPane().setLayout(frarticuloLayout);
        frarticuloLayout.setHorizontalGroup(
            frarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frarticuloLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(frarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frarticuloLayout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txbuscarART, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btaceptar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        frarticuloLayout.setVerticalGroup(
            frarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frarticuloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frarticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbuscarART, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btaceptar1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setText("Cliente");

        jLabel3.setText("Articulo");

        btcliente.setText("...");
        btcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclienteActionPerformed(evt);
            }
        });

        btarticulo.setText("...");
        btarticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btarticuloActionPerformed(evt);
            }
        });

        txarticulo.setEditable(false);

        jLabel4.setText("Fecha Entrega");

        jLabel5.setText("Fecha Devolucion");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Prestamo");

        jLabel6.setText("Tipo");

        txtipo.setEditable(false);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btprestar.setText("Prestar");
        btprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txarticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txtipo, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateentre, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(datedevol, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btarticulo)
                            .addComponent(btcliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btarticulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btcliente)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(datedevol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btprestar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclienteActionPerformed
        // TODO add your handling code here:
        
          frcliente.setVisible(true);
         
    }//GEN-LAST:event_btclienteActionPerformed

    private void btarticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btarticuloActionPerformed
        // TODO add your handling code here:
        frarticulo.setVisible(true);
    }//GEN-LAST:event_btarticuloActionPerformed

    private void txbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbuscarKeyPressed
        // TODO add your handling code here:
        String sql;
        if(!txbuscar.getText().equals("")){
            sql="SELECT * FROM clientes WHERE nombre LIKE '"+txbuscar.getText()+"%'";
        } else
            sql="SELECT * FROM clientes";
        buscarDatosCliente(sql);
}//GEN-LAST:event_txbuscarKeyPressed

    private void txbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbuscarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txbuscarActionPerformed

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        // TODO add your handling code here:
        int i=tabla.getSelectedRow();
        String dato=(String)tabla.getValueAt(i,0);//codigo
        txcodigo.setText(dato);
        dato=(String)tabla.getValueAt(i,1);//codigo
        txnombre.setText(dato);
    }//GEN-LAST:event_tablaMousePressed

    private void btaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaceptarActionPerformed
        // TODO add your handling code here:
        frcliente.setVisible(false);
}//GEN-LAST:event_btaceptarActionPerformed

    private void btaceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaceptar1ActionPerformed
        // TODO add your handling code here:
        frarticulo.setVisible(false);
    }//GEN-LAST:event_btaceptar1ActionPerformed

    private void tablaARTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaARTMousePressed
        // TODO add your handling code here:
        int i=tablaART.getSelectedRow();
        String dato=(String)tablaART.getValueAt(i,1);//codigo
        txarticulo.setText(dato);
        dato=(String)tablaART.getValueAt(i,3);//tipo
        txtipo.setText(dato);
    }//GEN-LAST:event_tablaARTMousePressed

    private void txbuscarARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbuscarARTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbuscarARTActionPerformed

    private void txbuscarARTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbuscarARTKeyPressed
        // TODO add your handling code here:
        String sql;
        if(!txbuscarART.getText().equals("")){
            sql="SELECT a.id_art, a.titulo, a.asignatura, t.nombre, a.autor, a.temas, a.cantidad  FROM articulos a, tipo t WHERE a.tipo= t.cod AND titulo LIKE '"+txbuscarART.getText()+"%'";
        } else
            sql="SELECT a.id_art, a.titulo, a.asignatura, t.nombre, a.autor, a.temas, a.cantidad  FROM articulos a, tipo t WHERE a.tipo= t.cod";
        buscarDatosArticulos(sql);
    }//GEN-LAST:event_txbuscarARTKeyPressed

    private void btprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprestarActionPerformed
        // TODO add your handling code here:
        String sql="SELECT COUNT(cod_prest) FROM prestamo WHERE cod_cliente="+txcodigo.getText();
        ResultSet con; int total=0,cant=0,faltantes=0,prestar=1;
        try
        {
            con=DataBase.Query(sql);
            if(con.next())
            {
              total=con.getInt(1);
            }
            if(total<3){
                 con=DataBase.Query("SELECT a.cantidad FROM articulos a  WHERE a.titulo='"+txarticulo.getText()+"'");
            if(con.next())
            {
              cant=con.getInt(1);
            }
                 if(cant > 0){//cantidad de articulos es mayor a 0
                     String fecha=fecha();
		

                     String consulta="SELECT  DATEDIFF('"+fecha+"','fecha_dev')  FROM prestamo WHERE cod_cliente='"+txcodigo.getText()+"' AND estado=1";
                     con =DataBase.Query(consulta);
                     if(con.next()){
                         faltantes=con.getInt(1);
                                 if (faltantes>0){
                                     prestar=0;
                                      javax.swing.JOptionPane.showMessageDialog(null, "Usted tiene una Fecha vencida!!");
                                     con.next();
                                     con.next();

                                   }
                       javax.swing.JOptionPane.showMessageDialog(null, dateentre.getText());
                     }
                     
                     if(prestar >0){
                         


                     sql="INSERT INTO prestamo VALUES ('auto','"+txcodigo.getText()+"','";
                     sql+=dateentre.getText()+"','";
                     sql+=datedevol.getText()+"','"+txarticulo.getText()+"','"+txtipo.getText()+"','1');";
                       DataBase.Execute(sql);

                       //restamos una unidad a la cantidad total
                       sql="UPDATE articulos SET cantidad="+(cant-1)+" WHERE titulo='"+txarticulo.getText()+"'";
                       DataBase.Execute(sql);
                       javax.swing.JOptionPane.showMessageDialog(null, "Articulo Prestado");
                     }
                 }
                 else
                 javax.swing.JOptionPane.showMessageDialog(null, "No se puede hacer el prestamo \n La Cantidad de articulos es 0");

            }
            else
                javax.swing.JOptionPane.showMessageDialog(null, "El Cliente Tiene mas de 3 Prestamos \n No se puede hacer el prestamo");

            }
        catch(SQLException exc)
        {
           System.err.println(exc.getMessage());
         }

    }//GEN-LAST:event_btprestarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frprincipal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
public void buscarDatosCliente(String SQL)
    {
        String titulos[]={"Codigo","Nombre"};

        int j,total1=0;
        ResultSet con;
        try
        {

            con=DataBase.Query("SELECT COUNT(*) FROM clientes");
            if(con.next())
            {
              total1=con.getInt(1);
            }
            Object [][] data = new Object[total1][4];

            con=DataBase.Query(SQL);
            j=0;
            while(con.next())
            {
                data[j][0]=con.getString(1);//codigo
                data[j][1]=con.getString(2);//Nombre

                j++;
            }//end while
           // DefaultTableModel ob =new DefaultTableModel();
            DefaultTableModel dtm = new DefaultTableModel(data,titulos);
            tabla.setModel(dtm);
        }
        catch(SQLException exc)
        {
           System.err.println(exc.getMessage());
         }
    }

    public void buscarDatosArticulos(String SQL)
    {
        String titulos[]={"Codigo","Titulo","Asignatura","Tipo","Autor","Tema","Cantidad"};

        int i,total=0;
        ResultSet con;
        try
        {

            con=DataBase.Query("SELECT COUNT(*) FROM articulos");
            if(con.next())
            {
              total=con.getInt(1);
            }
            Object [][] data = new Object[total][8];

            con=DataBase.Query(SQL);
            i=0;
            while(con.next())
            {
                data[i][0]=con.getString(1);//codigo
                data[i][1]=con.getString(2);//Titulo
                data[i][2]=con.getString(3);//Asignatura
                data[i][3]=con.getString(4);//Tipo
                data[i][4]=con.getString(5);//Autor
                data[i][5]=con.getString(6);//Tema
                data[i][6]=con.getString(7);//Cantidad
                
                i++;
            }//end while
           // DefaultTableModel ob =new DefaultTableModel();
            DefaultTableModel dtm = new DefaultTableModel(data,titulos);
            tablaART.setModel(dtm);
        }
        catch(SQLException exc)
        {
           System.err.println(exc.getMessage());
         }
    }

    

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaceptar;
    private javax.swing.JButton btaceptar1;
    private javax.swing.JButton btarticulo;
    private javax.swing.JButton btcliente;
    private javax.swing.JButton btprestar;
    private javax.swing.JTextField datedevol;
    private javax.swing.JTextField dateentre;
    private javax.swing.JFrame frarticulo;
    private javax.swing.JFrame frcliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaART;
    private javax.swing.JTextField txarticulo;
    private javax.swing.JTextField txbuscar;
    private javax.swing.JTextField txbuscarART;
    private javax.swing.JTextField txcodigo;
    private javax.swing.JTextField txnombre;
    private javax.swing.JTextField txtipo;
    // End of variables declaration//GEN-END:variables

}
